---

- name: disable selinux
  selinux:
    state: disabled


- name: set net.bridge.bridge-nf-call-ip6tables 1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1

- name: set net.bridge.bridge-nf-call-iptables 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1


- name: set net.ipv4.ip_forward 1
  sysctl:
    name: net.ipv4.ip_forward
    value: 1

- name: copy kubelet kubeadm kubectl rpm
  copy:
    src: /opt/kubernetes/rpm/{{ item }}
    dest: /tmp/
  with_items: 
    - kubelet-1.11.5-0.x86_64.rpm
    - kubeadm-1.11.5-0.x86_64.rpm
    - kubectl-1.11.5-0.x86_64.rpm
    - cri-tools-1.11.1-0.x86_64.rpm
    - kubernetes-cni-0.6.0-0.x86_64.rpm
 

- name: install kubelet 
  yum:
    name:
      - /tmp/kubelet-1.11.5-0.x86_64.rpm  
      - /tmp/kubeadm-1.11.5-0.x86_64.rpm  
      - /tmp/kubectl-1.11.5-0.x86_64.rpm  
      - /tmp/cri-tools-1.11.1-0.x86_64.rpm
      - /tmp/kubernetes-cni-0.6.0-0.x86_64.rpm

- name: config system kubelet
  systemd:
    name: kubelet 
    enabled: yes
    state: restarted

- name: add hosts
  lineinfile:
    path: /etc/hosts
    line: '10.16.16.8 api.kubernetes.local'
  tags: 
    - hosts



- name: copy images
  copy:
    src: /opt/kubernetes/images/{{ item }}
    dest: /tmp/
  with_items: 
    - kube-apiserver-amd64.tar
    - kube-scheduler-amd64.tar
    - kube-controller-manager-amd64.tar
    - kube-proxy-amd64.tar 
    - pause-3.1.tar 
    - coredns.tar 
    - flannel.tar
    - nginx.tar
  tags:
    - images 

- name: load kubernetes 
  command: docker load -i /tmp/{{ item }}
  with_items: 
    - kube-apiserver-amd64.tar
    - kube-scheduler-amd64.tar
    - kube-controller-manager-amd64.tar
    - kube-proxy-amd64.tar 
    - pause-3.1.tar 
    - coredns.tar 
    - flannel.tar
    - nginx.tar
  tags:
    - images 
