kind: Service
apiVersion: v1
metadata: 
  name: mysql-2
  labels: 
    kubernetes.io/name: "mysql-2"
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec: 
  ports: 
    - name: mysql 
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector: 
    app: mysql-2
