apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
    character-set-server=utf8
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only

