---

- hosts: all
  vars:
    etcd_0: 10.16.16.4
    etcd_1: 10.16.16.5
    etcd_2: 10.16.16.6
 
  tasks:
    #- include_tasks: tasks/etcd_task.yml 
    - import_tasks: tasks/docker.yml 
    #- import_tasks: tasks/kubernetes.yml 
